/* empty css                      */import{a as L,S as q,i}from"./assets/vendor-DhWfHwn5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const S="46359106-f72dd377f08be81b63b245749",b="https://pixabay.com/api/";let m=1;const v=async s=>{const r=`${b}?key=${S}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${m}`;try{return(await L.get(r)).data.hits}catch{throw new Error("Error fetching images")}},w=()=>{m+=1},$=()=>{m=1},P=new q(".gallery a",{captionDelay:250,captionsData:"alt"}),E=s=>{const r=document.querySelector(".gallery");if(r.innerHTML="",s.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}const o=s.map(({webformatURL:c,largeImageURL:e,tags:t,likes:n,views:h,comments:f,downloads:p})=>`<li class="gallery-item">
            <a href="${e}" class="gallery-link">
                <img src="${c}" alt="${t}" />
            </a>
            <div class="image-info">
                <span>Likes: ${n}</span>
                <span>Views: ${h}</span>
                <span>Comments: ${f}</span>
                <span>Downloads: ${p}</span>
            </div>
        </li>`).join("");r.innerHTML=o,P.refresh()},u=document.querySelector(".search-form"),a=document.querySelector(".load-more"),g=document.querySelector(".loader");let d="",l=[];u.addEventListener("submit",async s=>{if(s.preventDefault(),d=u.elements.query.value.trim(),!d){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}$(),a.classList.add("hidden"),l=[],document.querySelector(".gallery").innerHTML="",await y()});a.addEventListener("click",async()=>{w(),await y()});const y=async()=>{var s;try{g.classList.remove("hidden");const r=await v(d);if(r.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"}),a.classList.add("hidden");return}l=[...l,...r],E(l),r.length<15?(a.classList.add("hidden"),i.info({message:"We're sorry, but you've reached the end of search results."})):a.classList.remove("hidden");const o=((s=document.querySelector(".gallery-item"))==null?void 0:s.getBoundingClientRect().height)||0;window.scrollBy({top:o*2,behavior:"smooth"})}catch(r){console.error(r),i.error({message:"Error fetching images."})}finally{g.classList.add("hidden")}};a.style.marginBottom="32px";
//# sourceMappingURL=index.js.map
